#!/bin/bash
dconf write "/org/gnome/desktop/wm/keybindings/toggle-shaded" "['disabled']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/screensaver" "['disabled']"
dconf write "/org/gnome/settings-daemon/plugins/media-keys/terminal" "['disabled']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-down" "['disabled']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-up" "['disabled']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left" "['disabled']"
dconf write "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right" "['disabled']"
dconf write "/org/gnome/desktop/wm/keybindings/begin-move" "['disabled']"
dconf write "/org/gnome/desktop/wm/keybindings/begin-resize" "['disabled']"
